language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install: pip install -e .[test]
script:
- test -z "$STORMPATH_API_KEY_SECRET" || python setup.py test
- cd docs && make html
env:
  global:
  - secure: Q7sQSmMxZs0mfqgccUWr16rn38e+uFUbdIRaU0igYvIV24q80lXCWA5vvCwoSpa3AAVTEF4+XDaBdZl+HzD8PKjmAldljWIOi22fjoiyPtaA/+n5F9w8QbwmZ9T/pPfmHqr0yzYg89bsuGKJ7Irem1NdtOAozc2tVdfhhXI6NYM=
  - secure: CZOy1BN3piid5RgqjZRCQmYI6eZAQI+ojVb/pWA1APFFVNuQtKgAvsjI1zaQRx5xmiGFco1/BhSLBokwknh7MJcwxckpC5D7Y9Ccev4jbWG/2Gif3wjKlezBra2w6LheimcLvbkC+QKJ2n2oNI2xJxr95sBAMaQORJFXXD6Y2wg=
